export const dataAktifitasHarianPekerjaan = [
  {
    hariPekerjaan: "Senin",
    jamMulaiPekerjaan: "08:00",
    jamAkhirPekerjaan: "16:00",
    tempatPekerjaan: "Gedung A Lantai 2",
    uraianAktifitas: "Meeting proyek pengembangan sistem",
    fotoLokasiPekerjaan: "https://example.com/foto1.jpg",
    statusKehadiran: "hadir",
    tanggalDibuat: "2025-04-07T08:00:00Z",
    dibuatOleh: "admin1",
    tanggalUpdate: "2025-04-07T10:00:00Z",
    diupdateOleh: "admin1",
    isDeleted: 0
  },
  {
    hariPekerjaan: "Selasa",
    jamMulaiPekerjaan: "09:00",
    jamAkhirPekerjaan: "17:00",
    tempatPekerjaan: "Workshop B",
    uraianAktifitas: "Pengecekan alat berat",
    fotoLokasiPekerjaan: "https://example.com/foto2.jpg",
    statusKehadiran: "hadir",
    tanggalDibuat: "2025-04-06T09:30:00Z",
    dibuatOleh: "teknisi1",
    tanggalUpdate: "2025-04-06T12:00:00Z",
    diupdateOleh: "teknisi1",
    isDeleted: 0
  },
  {
    hariPekerjaan: "Rabu",
    jamMulaiPekerjaan: "10:00",
    jamAkhirPekerjaan: "15:00",
    tempatPekerjaan: "Lokasi Proyek C",
    uraianAktifitas: "Survey lapangan",
    fotoLokasiPekerjaan: "https://example.com/foto3.jpg",
    statusKehadiran: "ijin",
    tanggalDibuat: "2025-04-05T14:00:00Z",
    dibuatOleh: "admin2",
    tanggalUpdate: "2025-04-05T16:00:00Z",
    diupdateOleh: "admin2",
    isDeleted: 1
  },
  {
    hariPekerjaan: "Kamis",
    jamMulaiPekerjaan: "07:30",
    jamAkhirPekerjaan: "16:00",
    tempatPekerjaan: "Site D",
    uraianAktifitas: "Instalasi jaringan",
    fotoLokasiPekerjaan: "https://example.com/foto4.jpg",
    statusKehadiran: "hadir",
    tanggalDibuat: "2025-04-04T08:00:00Z",
    dibuatOleh: "teknisi2",
    tanggalUpdate: "2025-04-04T10:30:00Z",
    diupdateOleh: "teknisi2",
    isDeleted: 0
  },
  {
    hariPekerjaan: "Jumat",
    jamMulaiPekerjaan: "08:00",
    jamAkhirPekerjaan: "12:00",
    tempatPekerjaan: "Kantor Pusat",
    uraianAktifitas: "Rapat koordinasi mingguan",
    fotoLokasiPekerjaan: "https://example.com/foto5.jpg",
    statusKehadiran: "hadir",
    tanggalDibuat: "2025-04-03T07:00:00Z",
    dibuatOleh: "admin1",
    tanggalUpdate: "2025-04-03T08:30:00Z",
    diupdateOleh: "admin1",
    isDeleted: 0
  },
  {
    hariPekerjaan: "Senin",
    jamMulaiPekerjaan: "09:00",
    jamAkhirPekerjaan: "17:00",
    tempatPekerjaan: "Gudang Utama",
    uraianAktifitas: "Pemeriksaan stok barang",
    fotoLokasiPekerjaan: "https://example.com/foto6.jpg",
    statusKehadiran: "sakit",
    tanggalDibuat: "2025-04-02T09:15:00Z",
    dibuatOleh: "staff1",
    tanggalUpdate: "2025-04-02T10:00:00Z",
    diupdateOleh: "staff1",
    isDeleted: 1
  },
  {
    hariPekerjaan: "Selasa",
    jamMulaiPekerjaan: "08:30",
    jamAkhirPekerjaan: "15:30",
    tempatPekerjaan: "Gedung D Lantai 1",
    uraianAktifitas: "Pengujian sistem HVAC",
    fotoLokasiPekerjaan: "https://example.com/foto7.jpg",
    statusKehadiran: "cuti",
    tanggalDibuat: "2025-04-01T11:00:00Z",
    dibuatOleh: "teknisi3",
    tanggalUpdate: "2025-04-01T12:00:00Z",
    diupdateOleh: "teknisi3",
    isDeleted: 0
  },
  {
    hariPekerjaan: "Rabu",
    jamMulaiPekerjaan: "07:00",
    jamAkhirPekerjaan: "14:00",
    tempatPekerjaan: "Area Parkir",
    uraianAktifitas: "Perbaikan sistem drainase",
    fotoLokasiPekerjaan: "https://example.com/foto8.jpg",
    statusKehadiran: "hadir",
    tanggalDibuat: "2025-03-31T06:00:00Z",
    dibuatOleh: "admin2",
    tanggalUpdate: "2025-03-31T07:30:00Z",
    diupdateOleh: "admin2",
    isDeleted: 0
  },
  {
    hariPekerjaan: "Kamis",
    jamMulaiPekerjaan: "10:00",
    jamAkhirPekerjaan: "18:00",
    tempatPekerjaan: "Pabrik E",
    uraianAktifitas: "Pemeliharaan mesin produksi",
    fotoLokasiPekerjaan: "https://example.com/foto9.jpg",
    statusKehadiran: "tanpa keterangan",
    tanggalDibuat: "2025-03-30T09:45:00Z",
    dibuatOleh: "admin1",
    tanggalUpdate: "2025-03-30T10:30:00Z",
    diupdateOleh: "admin1",
    isDeleted: 1
  },
  {
    hariPekerjaan: "Jumat",
    jamMulaiPekerjaan: "08:00",
    jamAkhirPekerjaan: "12:00",
    tempatPekerjaan: "Kantor Cabang",
    uraianAktifitas: "Monitoring kinerja harian",
    fotoLokasiPekerjaan: "https://example.com/foto10.jpg",
    statusKehadiran: "hadir",
    tanggalDibuat: "2025-03-29T08:00:00Z",
    dibuatOleh: "staff2",
    tanggalUpdate: "2025-03-29T08:30:00Z",
    diupdateOleh: "staff2",
    isDeleted: 0
  }
];