export const dataJabatanPekerjaan = [
  {
    idPekerjaan: "PK001",
    kodePekerjaan: "KP-OPR-RKA",
    uraianPekerjaan: "Mengelola dan menginput data Rencana Kerja dan Anggaran",
    singkatanPekerjaan: "Operator RKA",
    kualifiksiPekerjaan: "Minimal S1 Ekonomi/Manajemen",
    hargaSatuanPekerjaan: 1500000,
    keterangan: "Diperlukan pada awal tahun anggaran",
    katgoriPekerjaan: "Perencanaan",
    status: "Aktif",
    tanggalDibuat: "2025-04-01T09:00:00Z",
    dibuatOleh: "admin1",
    tanggalUpdate: "2025-04-01T11:00:00Z",
    diupdateOleh: "admin1"
  },
  {
    idPekerjaan: "PK002",
    kodePekerjaan: "KP-SAKIP-01",
    uraianPekerjaan: "Mengelola Sistem Akuntabilitas Kinerja Instansi Pemerintah",
    singkatanPekerjaan: "Operator SAKIP",
    kualifiksiPekerjaan: "S1 Administrasi Negara",
    hargaSatuanPekerjaan: 1400000,
    keterangan: "Membantu pelaporan rutin",
    katgoriPekerjaan: "Evaluasi",
    status: "Aktif",
    tanggalDibuat: "2025-04-02T09:30:00Z",
    dibuatOleh: "admin2",
    tanggalUpdate: "2025-04-02T10:45:00Z",
    diupdateOleh: "admin2"
  },
  {
    idPekerjaan: "PK003",
    kodePekerjaan: "KP-ADM-001",
    uraianPekerjaan: "Mengelola administrasi surat-menyurat",
    singkatanPekerjaan: "Admin Surat",
    kualifiksiPekerjaan: "Minimal SMA/SMK",
    hargaSatuanPekerjaan: 1200000,
    keterangan: "Menangani surat masuk dan keluar",
    katgoriPekerjaan: "Administrasi",
    status: "Aktif",
    tanggalDibuat: "2025-03-30T08:00:00Z",
    dibuatOleh: "admin3",
    tanggalUpdate: "2025-03-31T09:00:00Z",
    diupdateOleh: "admin3"
  },
  {
    idPekerjaan: "PK004",
    kodePekerjaan: "KP-HELPDESK",
    uraianPekerjaan: "Memberikan bantuan teknis IT kepada pengguna",
    singkatanPekerjaan: "Helpdesk IT",
    kualifiksiPekerjaan: "D3 Teknik Informatika",
    hargaSatuanPekerjaan: 1350000,
    keterangan: "Bertugas selama jam kerja",
    katgoriPekerjaan: "Teknologi Informasi",
    status: "Aktif",
    tanggalDibuat: "2025-04-01T10:00:00Z",
    dibuatOleh: "admin1",
    tanggalUpdate: "2025-04-01T10:15:00Z",
    diupdateOleh: "admin1"
  },
  {
    idPekerjaan: "PK005",
    kodePekerjaan: "KP-CLEAN-001",
    uraianPekerjaan: "Membersihkan ruangan kerja dan fasilitas umum",
    singkatanPekerjaan: "Petugas Kebersihan",
    kualifiksiPekerjaan: "Tidak ada syarat khusus",
    hargaSatuanPekerjaan: 1000000,
    keterangan: "Disediakan per shift",
    katgoriPekerjaan: "Umum",
    status: "Aktif",
    tanggalDibuat: "2025-03-28T08:30:00Z",
    dibuatOleh: "admin3",
    tanggalUpdate: "2025-03-28T09:00:00Z",
    diupdateOleh: "admin3"
  },
  {
    idPekerjaan: "PK006",
    kodePekerjaan: "KP-PUSTAKAWAN",
    uraianPekerjaan: "Mengelola perpustakaan dan koleksi buku",
    singkatanPekerjaan: "Pustakawan",
    kualifiksiPekerjaan: "S1 Ilmu Perpustakaan",
    hargaSatuanPekerjaan: 1300000,
    keterangan: "Tugas bersifat harian",
    katgoriPekerjaan: "Layanan Umum",
    status: "Nonaktif",
    tanggalDibuat: "2025-03-25T09:45:00Z",
    dibuatOleh: "admin1",
    tanggalUpdate: "2025-04-01T08:30:00Z",
    diupdateOleh: "admin2"
  },
  {
    idPekerjaan: "PK007",
    kodePekerjaan: "KP-KONS-IT",
    uraianPekerjaan: "Konsultan implementasi sistem informasi",
    singkatanPekerjaan: "Konsultan IT",
    kualifiksiPekerjaan: "S2 Sistem Informasi",
    hargaSatuanPekerjaan: 2500000,
    keterangan: "Dibayar per proyek",
    katgoriPekerjaan: "Konsultasi",
    status: "Aktif",
    tanggalDibuat: "2025-03-27T13:00:00Z",
    dibuatOleh: "admin2",
    tanggalUpdate: "2025-03-27T13:15:00Z",
    diupdateOleh: "admin2"
  },
  {
    idPekerjaan: "PK008",
    kodePekerjaan: "KP-PENJAGA-MALAM",
    uraianPekerjaan: "Menjaga keamanan kantor di malam hari",
    singkatanPekerjaan: "Security Malam",
    kualifiksiPekerjaan: "Minimal SMA",
    hargaSatuanPekerjaan: 1100000,
    keterangan: "Tugas shift malam",
    katgoriPekerjaan: "Keamanan",
    status: "Aktif",
    tanggalDibuat: "2025-04-03T17:00:00Z",
    dibuatOleh: "admin1",
    tanggalUpdate: "2025-04-03T17:30:00Z",
    diupdateOleh: "admin1"
  },
  {
    idPekerjaan: "PK009",
    kodePekerjaan: "KP-SUPIR",
    uraianPekerjaan: "Menyediakan layanan transportasi dinas",
    singkatanPekerjaan: "Supir",
    kualifiksiPekerjaan: "Memiliki SIM A",
    hargaSatuanPekerjaan: 1200000,
    keterangan: "Dibayar bulanan",
    katgoriPekerjaan: "Transportasi",
    status: "Nonaktif",
    tanggalDibuat: "2025-02-15T08:00:00Z",
    dibuatOleh: "admin3",
    tanggalUpdate: "2025-03-01T08:00:00Z",
    diupdateOleh: "admin3"
  },
  {
    idPekerjaan: "PK010",
    kodePekerjaan: "KP-STAF-DATA",
    uraianPekerjaan: "Menginput dan mengelola data ke sistem informasi",
    singkatanPekerjaan: "Staf Data",
    kualifiksiPekerjaan: "Minimal D3 Statistik",
    hargaSatuanPekerjaan: 1400000,
    keterangan: "Wajib memiliki keterampilan komputer",
    katgoriPekerjaan: "Pengelolaan Data",
    status: "Aktif",
    tanggalDibuat: "2025-04-06T11:00:00Z",
    dibuatOleh: "admin2",
    tanggalUpdate: "2025-04-06T11:15:00Z",
    diupdateOleh: "admin2"
  }
];
